-- Habilitamos la extensión para poder manejar UUIDs nativamente en PostgreSQL
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 0. TABLA: cnae_mappings (Referencia para descripciones)
CREATE TABLE IF NOT EXISTS cnae_mappings (
    codigo VARCHAR(10) PRIMARY KEY,
    descripcion TEXT NOT NULL
);

INSERT INTO cnae_mappings (codigo, descripcion) VALUES
('011', 'Cultivos no perennes'),
('0111', 'Cultivo de cereales, distintos de arroz, leguminosas y oleaginosas'),
('0112', 'Cultivo de arroz'),
('0113', 'Cultivo de hortalizas, raíces y tubérculos'),
('0114', 'Cultivo de caña de azúcar'),
('0115', 'Cultivo de tabaco'),
('0116', 'Cultivo de plantas para fibras textiles'),
('0119', 'Otros cultivos no perennes'),
('012', 'Cultivos perennes'),
('0121', 'Cultivo de la vid'),
('0122', 'Cultivo de frutos tropicales y subtropicales'),
('0123', 'Cultivo de cítricos'),
('0124', 'Cultivo de frutos con hueso y pepitas'),
('0125', 'Cultivo de otros árboles y arbustos frutales y frutos secos'),
('0126', 'Cultivo de frutos oleaginosos'),
('0127', 'Cultivo de plantas para bebidas'),
('0128', 'Cultivo de especias, plantas aromáticas, medicinales y farmacéuticas'),
('0129', 'Otros cultivos perennes'),
('013', 'Propagación de plantas'),
('0130', 'Propagación de plantas'),
('014', 'Producción ganadera'),
('0141', 'Explotación de ganado bovino para la producción de leche'),
('0142', 'Explotación de otro ganado bovino y búfalos'),
('0143', 'Explotación de caballos y otros equinos'),
('0144', 'Explotación de camellos y otros camélidos'),
('0145', 'Explotación de ganado ovino y caprino'),
('0146', 'Explotación de ganado porcino'),
('0147', 'Avicultura   INE'),
('0148', 'Otras explotaciones de ganado'),
('015', 'Producción agrícola combinada con la producción ganadera'),
('0150', 'Producción agrícola combinada con la producción ganadera'),
('016', 'Actividades de apoyo a la agricultura, a la ganadería y de preparación  posterior a la cosecha'),
('0161', 'Actividades de apoyo a la agricultura'),
('0162', 'Actividades de apoyo a la ganadería'),
('0163', 'Actividades de preparación posterior a la cosecha y tratamiento de  semillas parareproducción'),
('017', 'Caza, captura de animales y servicios relacionados'),
('0170', 'Caza, captura de animales y servicios relacionados'),
('021', 'Silvicultura y otras actividades forestales'),
('0210', 'Silvicultura y otras actividades forestales'),
('022', 'Explotación de la madera'),
('0220', 'Explotación de la madera'),
('023', 'Recolección de productos silvestres, excepto madera'),
('0230', 'Recolección de productos silvestres, excepto madera'),
('024', 'Servicios de apoyo a la silvicultura'),
('0240', 'Servicios de apoyo a la silvicultura'),
('0311', 'Pesca marina'),
('0312', 'Pesca in agua dulce'),
('032', 'Acuicultura'),
('0321', 'Acuicultura marina'),
('0322', 'Acuicultura in agua dulce'),
('033', 'Actividades de apoyo a la pesca y la acuicultura'),
('0330', 'Actividades de apoyo a la pesca y la acuicultura   B INDUSTRIAS EXTRACTIVAS'),
('051', 'Extracción de antracita y hulla'),
('0510', 'Extracción de antracita y hulla   INE'),
('052', 'Extracción de lignito'),
('0520', 'Extracción de lignito'),
('061', 'Extracción de crudo de petróleo'),
('0610', 'Extracción de crudo de petróleo'),
('062', 'Extracción de gas natural'),
('0620', 'Extracción de gas natural'),
('071', 'Extracción de minerales de hierro'),
('0710', 'Extracción de minerales de hierro'),
('072', 'Extracción de minerales metálicos no férreos'),
('0721', 'Extracción de minerales de uranio y torio'),
('0729', 'Extracción de otros minerales metálicos no férreos'),
('081', 'Extracción de piedra, arena y arcilla'),
('0811', 'Extracción de piedra ornamental, piedra caliza, yeso, pizarra y otras  piedras'),
('0812', 'Extracción de gravas y arenas y extracción de arcilla y caolín'),
('089', 'Industrias extractivas n'),
('0891', 'Extracción de minerales para productos químicos y fertilizantes'),
('0892', 'Extracción de turba'),
('0893', 'Extracción de sal'),
('0899', 'Otras industrias extractivas n'),
('091', 'Actividades de apoyo a la extracción de petróleo y gas natural'),
('0910', 'Actividades de apoyo a la extracción de petróleo y gas natural'),
('099', 'Actividades de apoyo a otras industrias extractivas'),
('0990', 'Actividades de apoyo a otras industrias extractivas   C INDUSTRIA MANUFACTURERA'),
('101', 'Procesado y conservación de carne y elaboración de productos cárnicos'),
('1011', 'Procesado y conservación de carne, excepto volatería   INE'),
('1012', 'Procesado y conservación de volatería'),
('1013', 'Elaboración de productos cárnicos y de volatería'),
('102', 'Procesado y conservación de pescados, crustáceos y moluscos'),
('1021', 'Procesado de pescados, crustáceos y moluscos'),
('1022', 'Fabricación de conservas de pescado'),
('103', 'Procesado y conservación de frutas y hortalizas'),
('1031', 'Procesado y conservación de patatas'),
('1032', 'Elaboración de zumos de frutas y hortalizas'),
('1039', 'Otro procesado y conservación de frutas y hortalizas'),
('104', 'Fabricación de aceites y grasas vegetales y animales'),
('1042', 'Fabricación de margarina y grasas comestibles similares'),
('1043', 'Fabricación de aceite de oliva'),
('1044', 'Fabricación de otros aceites y grasas'),
('105', 'Fabricación de productos lácteos y hielo comestible'),
('1052', 'Fabricación de helados y otros hielos comestibles'),
('1053', 'Fabricación de quesos'),
('1054', 'Preparación de leche y otros productos lácteos'),
('106', 'Fabricación de productos de molinería, almidones y productos amiláceos'),
('1061', 'Fabricación de productos de molinería'),
('1062', 'Fabricación de almidones y productos amiláceos'),
('107', 'Fabricación de productos de panadería y pastas alimenticias'),
('1071', 'Fabricación de pan y de productos frescos de panadería y pastelería'),
('1072', 'Fabricación de galletas y productos de panadería y pastelería de larga  duración'),
('1073', 'Elaboración de pastas alimenticias'),
('108', 'Fabricación de otros productos alimenticios'),
('1081', 'Fabricación de azúcar'),
('1082', 'Fabricación de cacao, chocolate y productos de confitería'),
('1083', 'Elaboración de café, té e infusiones'),
('1084', 'Elaboración de especias, salsas y condimentos'),
('1085', 'Elaboración de platos y comidas preparados'),
('1086', 'Elaboración de preparados alimenticios homogeneizados y alimentos  dietéticos   INE'),
('1089', 'Elaboración de otros productos alimenticios n'),
('109', 'Fabricación de productos para la alimentación animal'),
('1091', 'Fabricación de productos para la alimentación de animales de granja'),
('1092', 'Fabricación de productos para la alimentación de animales de compañía'),
('110', 'Fabricación de bebidas'),
('1101', 'Destilación, rectificación y mezcla de bebidas alcohólicas'),
('1102', 'Elaboración de vinos'),
('1103', 'Elaboración de sidra y otras bebidas fermentadas a partir de frutas'),
('1104', 'Elaboración de otras bebidas no destiladas, procedentes de la  fermentación'),
('1105', 'Fabricación de cerveza'),
('1106', 'Fabricación de malta'),
('1107', 'Fabricación de bebidas no alcohólicas y aguas embotelladas'),
('120', 'Industria del tabaco'),
('1200', 'Industria del tabaco'),
('131', 'Preparación e hilado de fibras textiles'),
('1310', 'Preparación e hilado de fibras textiles'),
('132', 'Fabricación de tejidos textiles'),
('1320', 'Fabricación de tejidos textiles'),
('133', 'Acabado de textiles'),
('1330', 'Acabado de textiles'),
('139', 'Fabricación de otros productos textiles'),
('1391', 'Fabricación de tejidos de punto'),
('1392', 'Fabricación de textiles para el hogar y artículos de decoración  confeccionados'),
('1393', 'Fabricación de alfombras y moquetas'),
('1394', 'Fabricación de cuerdas, cordeles, bramantes y redes'),
('1395', 'Fabricación de telas no tejidas y artículos confeccionados con ellas'),
('1396', 'Fabricación de otros productos textiles de uso técnico e industrial'),
('1399', 'Fabricación de otros productos textiles n'),
('141', 'Confección de prendas de vestir de punto'),
('1410', 'Confección de prendas de vestir de punto'),
('142', 'Confección de otras prendas de vestir y accesorios'),
('1421', 'Confección de prendas de vestir exteriores'),
('1422', 'Confección de ropa interior'),
('1423', 'Confección de ropa de trabajo'),
('1424', 'Confección de prendas de vestir de cuero y peletería'),
('1429', 'Confección de otras prendas de vestir y accesorios n'),
('151', 'Preparación, teñido y curtido de cueros y pieles; fabricación de artículos  de marroquinería, viaje y de guarnicionería y talabartería'),
('1511', 'Preparación, curtido y teñido de cueros y pieles'),
('1512', 'Fabricación de artículos de marroquinería, viaje y de guarnicionería y  talabartería de cualquier material'),
('152', 'Fabricación de calzado'),
('1520', 'Fabricación de calzado'),
('161', 'Aserrado y cepillado de la madera; transformación y acabado de la  madera'),
('1611', 'Aserrado y cepillado de la madera'),
('1612', 'Transformación y acabado de la madera'),
('162', 'Fabricación de productos de madera, corcho, cestería y espartería'),
('1621', 'Fabricación de chapas y tableros de madera'),
('1622', 'Fabricación de suelos de madera ensamblados'),
('1623', 'Fabricación de otras estructuras de madera y piezas de carpintería y  ebanistería para la construcción, excepto las destinadas a construcción  industrializada'),
('1624', 'Fabricación de envases y embalajes de madera'),
('1625', 'Fabricación de puertas y ventanas de madera'),
('1626', 'Fabricación de combustibles sólidos a partir de biomasa vegetal'),
('1627', 'Acabado de productos de madera'),
('1628', 'Fabricación de otros productos de madera, artículos de corcho, cestería  y espartería   INE'),
('1629', 'Fabricación de otras estructuras de madera y piezas de carpintería y  ebanistería destinadas a la construcción industrializada'),
('171', 'Fabricación de pasta papelera, papel y cartón'),
('1711', 'Fabricación de pasta papelera'),
('1712', 'Fabricación de papel y cartón'),
('172', 'Fabricación de artículos de papel y de cartón'),
('1721', 'Fabricación de papel y cartón ondulados y de envases y embalajes de  papel y cartón'),
('1722', 'Fabricación de artículos de papel y cartón para uso doméstico, sanitario  e higiénico'),
('1723', 'Fabricación de artículos de papelería'),
('1724', 'Fabricación de papeles pintados'),
('1725', 'Fabricación de otros artículos de papel y cartón'),
('181', 'Artes gráficas y servicios relacionados'),
('1811', 'Impresión de periódicos'),
('1812', 'Otras actividades de impresión y artes gráficas'),
('1813', 'Servicios de preimpresión y preparación de soportes'),
('1814', 'Encuadernación y servicios relacionados'),
('182', 'Reproducción de soportes grabados'),
('1820', 'Reproducción de soportes grabados'),
('191', 'Coquerías'),
('1910', 'Coquerías'),
('192', 'Refino de petróleo y de combustibles fósiles'),
('1920', 'Refino de petróleo y de combustibles fósiles'),
('201', 'Fabricación de productos químicos básicos, compuestos nitrogenados,  fertilizantes, plásticos y caucho sintético in formas primarias'),
('2011', 'Fabricación de gases industriales'),
('2012', 'Fabricación de colorantes y pigmentos'),
('2013', 'Fabricación de otros productos básicos de química inorgánica   INE'),
('2014', 'Fabricación de otros productos básicos de química orgánica'),
('2015', 'Fabricación de fertilizantes y compuestos nitrogenados'),
('2016', 'Fabricación de plásticos in formas primarias'),
('2017', 'Fabricación de caucho sintético in formas primarias'),
('202', 'Fabricación de pesticidas, desinfectantes y otros productos agroquímicos'),
('2020', 'Fabricación de pesticidas, desinfectantes y otros productos agroquímicos'),
('203', 'Fabricación de pinturas, barnices y revestimientos similares, tintas de  imprenta y masillas'),
('2030', 'Fabricación de pinturas, barnices y revestimientos similares, tintas de  imprenta y masillas'),
('204', 'Fabricación de artículos de lavado, limpieza y abrillantamiento'),
('2041', 'Fabricación de jabones, detergentes y otros artículos de limpieza y  abrillantamiento'),
('2042', 'Fabricación de productos de perfumería y cosmética'),
('205', 'Fabricación de otros productos químicos'),
('2051', 'Fabricación de biocombustibles líquidos'),
('2059', 'Fabricación de otros productos químicos n'),
('206', 'Fabricación de fibras artificiales y sintéticas'),
('2060', 'Fabricación de fibras artificiales y sintéticas'),
('211', 'Fabricación de productos farmacéuticos de base'),
('2110', 'Fabricación de productos farmacéuticos de base'),
('212', 'Fabricación de especialidades farmacéuticas'),
('2120', 'Fabricación de especialidades farmacéuticas'),
('221', 'Fabricación de productos de caucho'),
('2211', 'Fabricación, recauchutado y reconstrucción de neumáticos de caucho y  fabricación de cámaras'),
('2212', 'Fabricación de otros productos de caucho'),
('222', 'Fabricación de productos de plástico'),
('2221', 'Fabricación de placas, hojas, tubos y perfiles de plástico'),
('2222', 'Fabricación de envases y embalajes de plástico'),
('2223', 'Fabricación de puertas y ventanas de plástico   INE'),
('2224', 'Fabricación de productos de plástico para la construcción'),
('2225', 'Transformación y acabado de productos de plástico'),
('2226', 'Fabricación de otros productos de plástico'),
('231', 'Fabricación de vidrio y productos de vidrio'),
('2311', 'Fabricación de vidrio plano'),
('2312', 'Manipulado y transformación de vidrio plano'),
('2313', 'Fabricación de vidrio hueco'),
('2314', 'Fabricación de fibra de vidrio'),
('2315', 'Fabricación y manipulado de otro vidrio, incluido el vidrio técnico'),
('232', 'Fabricación de productos cerámicos refractarios'),
('2320', 'Fabricación de productos cerámicos refractarios'),
('233', 'Fabricación de productos cerámicos para la construcción'),
('2331', 'Fabricación de azulejos y baldosas de cerámica'),
('2332', 'Fabricación de ladrillos, tejas y productos de tierras cocidas para la  construcción'),
('234', 'Fabricación de otros productos cerámicos'),
('2341', 'Fabricación de artículos cerámicos de uso doméstico y ornamental'),
('2342', 'Fabricación de aparatos sanitarios cerámicos'),
('2343', 'Fabricación de aisladores y piezas aislantes de material cerámico'),
('2344', 'Fabricación de otros productos cerámicos de uso técnico'),
('2345', 'Fabricación de otros productos cerámicos'),
('235', 'Fabricación de cemento, cal y yeso'),
('2351', 'Fabricación de cemento'),
('2352', 'Fabricación de cal y yeso'),
('236', 'Fabricación de elementos de hormigón, cemento y yeso'),
('2362', 'Fabricación de elementos de yeso para la construcción'),
('2363', 'Fabricación de hormigón fresco'),
('2364', 'Fabricación de mortero'),
('2365', 'Fabricación de fibrocemento'),
('2366', 'Fabricación de otros productos de hormigón, yeso y cemento'),
('2367', 'Fabricación de elementos de hormigón para la construcción no  industrializada   INE'),
('2368', 'Fabricación de elementos de hormigón para la construcción  industrializada'),
('237', 'Corte, tallado y acabado de la piedra'),
('2370', 'Corte, tallado y acabado de la piedra'),
('239', 'Fabricación de productos abrasivos y productos minerales no metálicos  n'),
('2391', 'Fabricación de productos abrasivos'),
('2399', 'Fabricación de otros productos minerales no metálicos n'),
('241', 'Fabricación de productos básicos de hierro, acero y ferroaleaciones'),
('2410', 'Fabricación de productos básicos de hierro, acero y ferroaleaciones'),
('242', 'Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de  acero'),
('2420', 'Fabricación de tubos, tuberías, perfiles huecos y sus accesorios, de  acero'),
('243', 'Fabricación de otros productos de primera transformación del acero'),
('2431', 'Estirado in frío'),
('2432', 'Laminado in frío'),
('2433', 'Producción de perfiles in frío por conformación con plegado'),
('2434', 'Trefilado in frío'),
('244', 'Producción de metales preciosos y de otros metales no férreos'),
('2441', 'Producción de metales preciosos'),
('2442', 'Producción de aluminio'),
('2443', 'Producción de plomo, zinc y estaño'),
('2444', 'Producción de cobre'),
('2445', 'Producción de otros metales no férreos'),
('2446', 'Procesamiento de combustibles nucleares'),
('245', 'Fundición de metales'),
('2451', 'Fundición de hierro'),
('2452', 'Fundición de acero'),
('2453', 'Fundición de metales ligeros'),
('2454', 'Fundición de otros metales no férreos'),
('251', 'Fabricación de elementos metálicos para la construcción'),
('2512', 'Fabricación de puertas y ventanas de metal'),
('2513', 'Fabricación de estructuras metálicas y sus componentes, excepto las  destinadas a construcción industrializada'),
('2514', 'Fabricación de estructuras metálicas y sus componentes destinadas a  construcción industrializada'),
('252', 'Fabricación de cisternas, grandes depósitos y contenedores de metal'),
('2521', 'Fabricación de radiadores, generadores de vapor y calderas para  calefacción central'),
('2522', 'Fabricación de otras cisternas, grandes depósitos y contenedores de  metal'),
('253', 'Fabricación de armas y municiones'),
('2530', 'Fabricación de armas y municiones'),
('254', 'Forja y modelado de metales y metalurgia de polvos'),
('2540', 'Forja y modelado de metales y metalurgia de polvos'),
('255', 'Tratamiento, revestimiento y mecanizado de metales'),
('2551', 'Revestimiento de metales'),
('2552', 'Tratamiento térmico de metales'),
('2553', 'Mecanizado de metales'),
('256', 'Fabricación de artículos de cuchillería y cubertería, herramientas y  ferretería'),
('2561', 'Fabricación de artículos de cuchillería y cubertería'),
('2562', 'Fabricación de cerraduras y herrajes'),
('2563', 'Fabricación de herramientas'),
('259', 'Fabricación de otros productos metálicos'),
('2591', 'Fabricación de bidones y toneles de hierro o acero'),
('2592', 'Fabricación de envases y embalajes metálicos ligeros'),
('2593', 'Fabricación de productos de alambre, cadenas y muelles'),
('2594', 'Fabricación de pernos y productos de tornillería'),
('2599', 'Fabricación de otros productos metálicos n'),
('261', 'Fabricación de componentes electrónicos y circuitos impresos  ensamblados'),
('2611', 'Fabricación de componentes electrónicos   INE'),
('2612', 'Fabricación de circuitos impresos ensamblados'),
('262', 'Fabricación de ordenadores y equipos periféricos'),
('2620', 'Fabricación de ordenadores y equipos periféricos'),
('263', 'Fabricación de equipos de telecomunicaciones'),
('2630', 'Fabricación de equipos de telecomunicaciones'),
('264', 'Fabricación de productos electrónicos de consumo'),
('2640', 'Fabricación de productos electrónicos de consumo'),
('265', 'Fabricación de instrumentos de verificación de medidas y relojes'),
('2651', 'Fabricación de instrumentos y aparatos de medida, verificación y  navegación'),
('2652', 'Fabricación de relojes'),
('266', 'Fabricación de equipos de radiación, electromédicos y  electroterapéuticos'),
('2660', 'Fabricación de equipos de radiación, electromédicos y  electroterapéuticos'),
('267', 'Fabricación de instrumentos ópticos, soportes magnéticos y ópticos y  equipos fotográficos'),
('2670', 'Fabricación de instrumentos ópticos, soportes magnéticos y ópticos y  equipos fotográficos'),
('271', 'Fabricación de motores, generadores y transformadores eléctricos, y de  aparatos de distribución y control eléctrico'),
('2711', 'Fabricación de motores, generadores y transformadores eléctricos'),
('2712', 'Fabricación de aparatos de distribución y control eléctrico'),
('272', 'Fabricación de pilas y acumuladores eléctricos'),
('2720', 'Fabricación de pilas y acumuladores eléctricos'),
('273', 'Fabricación de cables y dispositivos de cableado'),
('2731', 'Fabricación de cables de fibra óptica'),
('2732', 'Fabricación de otros hilos y cables electrónicos y eléctricos'),
('2733', 'Fabricación de dispositivos de cableado'),
('274', 'Fabricación de equipos de iluminación'),
('2740', 'Fabricación de equipos de iluminación'),
('275', 'Fabricación de aparatos domésticos'),
('2751', 'Fabricación de electrodomésticos   INE'),
('2752', 'Fabricación de aparatos domésticos no eléctricos'),
('279', 'Fabricación de otro material y equipo eléctrico'),
('2790', 'Fabricación de otro material y equipo eléctrico'),
('281', 'Fabricación de maquinaria de uso general'),
('2811', 'Fabricación de motores y turbinas, excepto los destinados a aeronaves,  vehículos automóviles y ciclomotores'),
('2812', 'Fabricación de equipos de transmisión hidráulica y neumática'),
('2813', 'Fabricación de otras bombas y compresores'),
('2814', 'Fabricación de otra grifería y válvulas'),
('2815', 'Fabricación de cojinetes, engranajes y órganos mecánicos de  transmisión'),
('282', 'Fabricación de otra maquinaria de uso general'),
('2821', 'Fabricación de hornos, quemadores y equipos de calefacción doméstica  permanente'),
('2822', 'Fabricación de maquinaria de elevación y manipulación'),
('2823', 'Fabricación de máquinas y equipos de oficina, excepto equipos  informáticos'),
('2824', 'Fabricación de herramientas eléctricas manuales'),
('2825', 'Fabricación de equipos de aire acondicionado no domésticos'),
('2829', 'Fabricación de otra maquinaria de uso general n'),
('283', 'Fabricación de maquinaria agraria y forestal'),
('2830', 'Fabricación de maquinaria agraria y forestal'),
('284', 'Fabricación de maquinaria para el conformado de metales y de  máquinas herramienta'),
('2841', 'Fabricación de maquinaria para el conformado de metales y de otras  máquinas herramienta para trabajar el metal'),
('2842', 'Fabricación de otras máquinas herramienta'),
('289', 'Fabricación de otra maquinaria para usos específicos'),
('2891', 'Fabricación de maquinaria para la industria metalúrgica'),
('2892', 'Fabricación de maquinaria para las industrias extractivas y de la  construcción'),
('2893', 'Fabricación de maquinaria para la industria de la alimentación, bebidas y  tabaco'),
('2894', 'Fabricación de maquinaria para las industrias textil, de la confección y  del cuero   INE'),
('2895', 'Fabricación de maquinaria para la industria del papel y del cartón'),
('2896', 'Fabricación de maquinaria para las industrias del plástico y del caucho'),
('2897', 'Fabricación de maquinaria de fabricación aditiva'),
('2899', 'Fabricación de otra maquinaria para usos específicos n'),
('291', 'Fabricación de vehículos de motor'),
('2910', 'Fabricación de vehículos de motor'),
('292', 'Fabricación de carrocerías para vehículos de motor; fabricación de  remolques y semirremolques'),
('2920', 'Fabricación de carrocerías para vehículos de motor; fabricación de  remolques y semirremolques'),
('293', 'Fabricación de repuestos y accesorios de vehículos de motor'),
('2931', 'Fabricación de equipos eléctricos y electrónicos para vehículos de motor'),
('2932', 'Fabricación de otros componentes, piezas y accesorios para vehículos  de motor'),
('301', 'Construcción naval'),
('3011', 'Construcción de buques civiles y estructuras flotantes'),
('3012', 'Construcción de embarcaciones de recreo y deporte'),
('3013', 'Construcción de embarcaciones y buques militares'),
('302', 'Fabricación de locomotoras y material ferroviario'),
('3020', 'Fabricación de locomotoras y material ferroviario'),
('303', 'Construcción aeronáutica y espacial y su maquinaria'),
('3031', 'Construcción aeronáutica y espacial civil y su maquinaria'),
('3032', 'Construcción aeronáutica y espacial militar y su maquinaria'),
('304', 'Fabricación de vehículos militares de combate'),
('3040', 'Fabricación de vehículos militares de combate'),
('309', 'Fabricación de otro material de transporte n'),
('3091', 'Fabricación de motocicletas'),
('3092', 'Fabricación de bicicletas y de vehículos para personas con discapacidad'),
('3099', 'Fabricación de otro material de transporte n'),
('310', 'Fabricación de muebles   INE'),
('3100', 'Fabricación de muebles'),
('321', 'Fabricación de artículos de joyería, bisutería y similares'),
('3211', 'Fabricación de monedas'),
('3212', 'Fabricación de artículos de joyería y artículos similares'),
('3213', 'Fabricación de artículos de bisutería y artículos similares'),
('322', 'Fabricación de instrumentos musicales'),
('3220', 'Fabricación de instrumentos musicales'),
('323', 'Fabricación de artículos de deporte'),
('3230', 'Fabricación de artículos de deporte'),
('324', 'Fabricación de juegos y juguetes'),
('3240', 'Fabricación de juegos y juguetes'),
('325', 'Fabricación de instrumentos y suministros médicos y odontológicos'),
('3250', 'Fabricación de instrumentos y suministros médicos y odontológicos'),
('329', 'Industrias manufactureras n'),
('3291', 'Fabricación de escobas, brochas y cepillos'),
('3299', 'Otras industrias manufactureras n'),
('331', 'Reparación y mantenimiento de productos metálicos, maquinaria y  equipos'),
('3311', 'Reparación y mantenimiento de productos metálicos'),
('3312', 'Reparación y mantenimiento de maquinaria'),
('3313', 'Reparación y mantenimiento de equipos electrónicos y ópticos'),
('3314', 'Reparación y mantenimiento de equipos eléctricos'),
('3315', 'Reparación y mantenimiento de buques y embarcaciones civiles'),
('3316', 'Reparación y mantenimiento aeronáutico y espacial civil'),
('3317', 'Reparación y mantenimiento de otro material de transporte civil'),
('3318', 'Reparación y mantenimiento de vehículos de combate, buques,  embarcaciones, vehículos aéreos y espaciales militares'),
('3319', 'Reparación y mantenimiento de otros equipos'),
('332', 'Instalación de máquinas y equipos industriales'),
('3320', 'Instalación de máquinas y equipos industriales   INE'),
('351', 'Producción, transporte y distribución de energía eléctrica'),
('3511', 'Producción de energía eléctrica a partir de fuentes no renovables'),
('3512', 'Producción de energía eléctrica a partir de fuentes renovables'),
('3513', 'Transporte de energía eléctrica'),
('3514', 'Distribución de energía eléctrica'),
('3515', 'Comercio de energía eléctrica'),
('3516', 'Almacenamiento de energía eléctrica'),
('352', 'Producción de gas y distribución por tubería de combustibles gaseosos'),
('3521', 'Producción de gas'),
('3522', 'Distribución por tubería de combustibles gaseosos'),
('3523', 'Comercio de gas por tuberías'),
('3524', 'Almacenamiento de gas como parte de los servicios de suministro de la  red'),
('353', 'Suministro de vapor y aire acondicionado'),
('3530', 'Suministro de vapor y aire acondicionado'),
('354', 'Actividades de intermediación de energía eléctrica y gas natural'),
('3540', 'Actividades de intermediación de energía eléctrica y gas natural   E SUMINISTRO DE AGUA, ACTIVIDADES DE SANEAMIENTO,  GESTIÓN DE RESIDUOS Y DESCONTAMINACIÓN'),
('360', 'Captación, depuración y distribución de agua'),
('3600', 'Captación, depuración y distribución de agua'),
('370', 'Recogida y tratamiento de aguas residuales'),
('3700', 'Recogida y tratamiento de aguas residuales'),
('381', 'Recogida de residuos'),
('3811', 'Recogida de residuos no peligrosos'),
('3812', 'Recogida de residuos peligrosos'),
('382', 'Valorización de residuos   INE'),
('3821', 'Valorización de materiales'),
('3822', 'Valorización energética'),
('3823', 'Otra valorización de residuos'),
('383', 'Eliminación de residuos sin valorización'),
('3831', 'Incineración sin valorización energética'),
('3832', 'Depósito in vertederos o almacenamiento permanente'),
('3833', 'Otra eliminación de residuos'),
('390', 'Actividades de descontaminación y otros servicios de gestión de  residuos'),
('3900', 'Actividades de descontaminación y otros servicios de gestión de  residuos   F CONSTRUCCIÓN'),
('410', 'Construcción de edificios'),
('4101', 'Construcción de edificios residenciales'),
('4102', 'Construcción de edificios no residenciales'),
('421', 'Construcción de carreteras y vías férreas, puentes y túneles'),
('4211', 'Construcción de carreteras y autopistas'),
('4212', 'Construcción de vías férreas de superficie y subterráneas'),
('4213', 'Construcción de puentes y túneles'),
('422', 'Construcción de redes'),
('4221', 'Construcción de redes para fluidos'),
('4222', 'Construcción de redes eléctricas y de telecomunicaciones'),
('429', 'Construcción de otros proyectos de ingeniería civil'),
('4291', 'Obras hidráulicas'),
('4299', 'Construcción de otros proyectos de ingeniería civil n'),
('431', 'Demolición y preparación de terrenos'),
('4311', 'Demolición'),
('4312', 'Preparación de terrenos   INE'),
('4313', 'Perforaciones y sondeos'),
('432', 'Instalaciones eléctricas, de fontanería y otras instalaciones in obras de  construcción'),
('4321', 'Instalaciones eléctricas'),
('4322', 'Fontanería, instalación de sistemas de calefacción y aire acondicionado'),
('4323', 'Instalación de aislamientos'),
('4324', 'Otras instalaciones in obras de construcción'),
('433', 'Acabado de edificios'),
('4331', 'Revocamiento'),
('4332', 'Instalación de carpintería'),
('4333', 'Revestimiento de suelos y paredes'),
('4334', 'Pintura y acristalamiento'),
('4335', 'Otros acabados de edificios'),
('434', 'Actividades de construcción especializada in la construcción de edificios'),
('4341', 'Construcción de cubiertas'),
('4342', 'Otras actividades de construcción especializada in la construcción de  edificios'),
('435', 'Actividades de construcción especializada in ingeniería civil'),
('4350', 'Actividades de construcción especializada in ingeniería civil'),
('436', 'Actividades de intermediación para servicios de construcción  especializada'),
('4360', 'Actividades de intermediación para servicios de construcción  especializada'),
('439', 'Otras actividades de construcción especializada'),
('4391', 'Actividades de mampostería y albañilería'),
('4399', 'Otras actividades de construcción especializada n'),
('461', 'Intermediarios del comercio al por mayor'),
('4611', 'Actividades de intermediarios del comercio al por mayor de materias  primas agrarias, animales vivos, materias primas textiles y productos  semielaborados'),
('4612', 'Actividades de intermediarios del comercio al por mayor de  combustibles, minerales, metales y productos químicos industriales   INE'),
('4613', 'Actividades de intermediarios del comercio al por mayor de la madera y  materiales de construcción'),
('4614', 'Actividades de intermediarios del comercio al por mayor de maquinaria,  equipo industrial, embarcaciones y aeronaves'),
('4615', 'Actividades de intermediarios del comercio al por mayor de muebles,  artículos para el hogar y ferretería'),
('4616', 'Actividades de intermediarios del comercio al por mayor de textiles,  prendas de vestir, peletería, calzado y artículos de cuero'),
('4617', 'Actividades de intermediarios del comercio al por mayor de productos  alimenticios, bebidas y tabaco'),
('4618', 'Actividades de intermediarios del comercio al por mayor de otros  productos específicos'),
('4619', 'Actividades de los agentes del comercio al por mayor no especializado'),
('462', 'Comercio al por mayor de materias primas agrarias y de animales vivos'),
('4621', 'Comercio al por mayor de cereales, tabaco in rama, simientes y  alimentos para animales'),
('4622', 'Comercio al por mayor de flores y plantas'),
('4623', 'Comercio al por mayor de animales vivos'),
('4624', 'Comercio al por mayor de cueros y pieles'),
('463', 'Comercio al por mayor de productos alimenticios, bebidas y tabaco'),
('4631', 'Comercio al por mayor de frutas y hortalizas'),
('4632', 'Comercio al por mayor de carne, productos cárnicos; pescado y  productos del pescado'),
('4633', 'Comercio al por mayor de productos lácteos, huevos, aceites y grasas  comestibles'),
('4634', 'Comercio al por mayor de bebidas'),
('4635', 'Comercio al por mayor de productos del tabaco'),
('4636', 'Comercio al por mayor de azúcar, chocolate y confitería'),
('4637', 'Comercio al por mayor de café, té, cacao y especias'),
('4638', 'Comercio al por mayor de otros alimentos'),
('4639', 'Comercio al por mayor, no especializado, de productos alimenticios,  bebidas y tabaco'),
('464', 'Comercio al por mayor de artículos de uso doméstico'),
('4641', 'Comercio al por mayor de textiles'),
('4642', 'Comercio al por mayor de prendas de vestir y calzado'),
('4643', 'Comercio al por mayor de aparatos electrodomésticos   INE'),
('4644', 'Comercio al por mayor de porcelana, cristalería y artículos de limpieza'),
('4645', 'Comercio al por mayor de productos de perfumería y cosmética'),
('4646', 'Comercio al por mayor de productos farmacéuticos y médicos'),
('4647', 'Comercio al por mayor de muebles para el hogar, oficinas y  establecimientos comerciales, alfombras y aparatos de iluminación'),
('4648', 'Comercio al por mayor de artículos de relojería y joyería'),
('4649', 'Comercio al por mayor de otros artículos de uso doméstico'),
('465', 'Comercio al por mayor of equipos para las tecnologías of la información  y las comunicaciones'),
('4650', 'Comercio al por mayor of equipos para las tecnologías of la información  y las comunicaciones'),
('466', 'Comercio al por mayor of otra maquinaria, equipos y suministros'),
('4661', 'Comercio al por mayor of maquinaria, equipos y suministros agrícolas'),
('4662', 'Comercio al por mayor of máquinas herramienta'),
('4663', 'Comercio al por mayor of maquinaria para la minería, la construcción y  la ingeniería civil'),
('4664', 'Comercio al por mayor of otra maquinaria y equipo'),
('467', 'Comercio al por mayor of vehículos of motor, motocicletas y sus  repuestos y accesorios'),
('4671', 'Comercio al por mayor of vehículos of motor'),
('4672', 'Comercio al por mayor of repuestos y accesorios of vehículos of motor'),
('4673', 'Comercio al por mayor of motocicletas, y repuestos y accesorios of  motocicletas'),
('468', 'Otro comercio al por mayor especializado'),
('4681', 'Comercio al por mayor of combustibles sólidos, líquidos y gaseosos, y  productos similares'),
('4682', 'Comercio al por mayor of metales y minerales metálicos'),
('4683', 'Comercio al por mayor of madera, materiales of construcción y aparatos  sanitarios'),
('4684', 'Comercio al por mayor of equipos y suministros of ferretería, fontanería  y calefacción'),
('4685', 'Comercio al por mayor of productos químicos'),
('4686', 'Comercio al por mayor of otros productos semielaborados'),
('4687', 'Comercio al por mayor of chatarra y productos of desecho'),
('4689', 'Otro comercio al por mayor especializado n'),
('469', 'Comercio al por mayor no especializado   INE'),
('4690', 'Comercio al por mayor no especializado'),
('471', 'Comercio al por menor no especializado'),
('4711', 'Comercio al por menor no especializado con predominio of productos  alimenticios, bebidas y tabaco'),
('4712', 'Otro comercio al por menor no especializado'),
('472', 'Comercio al por menor of productos alimenticios, bebidas y tabaco'),
('4721', 'Comercio al por menor of frutas y verduras'),
('4722', 'Comercio al por menor of carne y productos cárnicos'),
('4723', 'Comercio al por menor of pescados y mariscos'),
('4724', 'Comercio al por menor of pan, productos of panadería y confitería'),
('4725', 'Comercio al por menor of bebidas'),
('4726', 'Comercio al por menor of productos of tabaco'),
('4727', 'Comercio al por menor of otros productos alimenticios'),
('473', 'Comercio al por menor of combustible para la automoción'),
('4730', 'Comercio al por menor of combustible para la automoción'),
('474', 'Comercio al por menor of equipos para las tecnologías of la información  y las comunicaciones'),
('4740', 'Comercio al por menor of equipos para las tecnologías of la información  y las comunicaciones'),
('475', 'Comercio al por menor of otros artículos of uso doméstico'),
('4751', 'Comercio al por menor of textiles'),
('4752', 'Comercio al por menor of ferretería, materiales of construcción, pinturas  y vidrio'),
('4753', 'Comercio al por menor of alfombras, moquetas y revestimientos of  paredes y suelos'),
('4754', 'Comercio al por menor of aparatos electrodomésticos'),
('4755', 'Comercio al por menor of muebles, aparatos of iluminación, vajilla y  otros artículos of uso doméstico'),
('476', 'Comercio al por menor of artículos culturales y recreativos'),
('4761', 'Comercio al por menor of libros'),
('4762', 'Comercio al por menor of periódicos y otras publicaciones periódicas y  artículos of papelería'),
('4763', 'Comercio al por menor of artículos deportivos'),
('4764', 'Comercio al por menor of juegos y juguetes   INE'),
('4769', 'Comercio al por menor of artículos culturales y recreativos n'),
('477', 'Comercio al por menor of otros artículos, excepto vehículos of motor y  motocicletas'),
('4771', 'Comercio al por menor of prendas of vestir'),
('4772', 'Comercio al por menor of calzado y artículos of cuero'),
('4773', 'Comercio al por menor of productos farmacéuticos'),
('4774', 'Comercio al por menor of artículos médicos y ortopédicos'),
('4775', 'Comercio al por menor of productos of cosmética e higiene'),
('4776', 'Comercio al por menor of flores, plantas, fertilizantes, animales of  compañía y alimentos para estos'),
('4777', 'Comercio al por menor of articles of relojería y joyería'),
('4778', 'Comercio al por menor of otros productos nuevos'),
('4779', 'Comercio al por menor of artículos of segunda mano'),
('478', 'Comercio al por menor of vehículos of motor, motocicletas y sus  repuestos y accesorios'),
('4781', 'Comercio al por menor of vehículos of motor'),
('4782', 'Comercio al por menor of repuestos y accesorios of vehículos of motor'),
('4783', 'Comercio al por menor of motocicletas, y repuestos y accesorios of  motocicletas'),
('479', 'Actividades of servicios of intermediación para el comercio al por menor'),
('4791', 'Actividades of servicios of intermediación para el comercio al por menor  no especializado'),
('4792', 'Actividades of servicios of intermediación para el comercio al por menor  especializado   H TRANSPORTE Y ALMACENAMIENTO'),
('491', 'Transporte of pasajeros por ferrocarril'),
('4911', 'Transporte pesado of pasajeros por ferrocarril'),
('4912', 'Otro transporte of pasajeros por ferrocarril'),
('492', 'Transporte of mercancías por ferrocarril'),
('4920', 'Transporte of mercancías por ferrocarril'),
('493', 'Otro transporte terrestre of pasajeros'),
('4931', 'Transporte regular of pasajeros por carretera'),
('4932', 'Transporte no regular of pasajeros por carretera   INE'),
('4933', 'Servicios of transporte of pasajeros bajo demanda in vehículos con  conductor'),
('4934', 'Transporte of pasajeros in teleféricos y remontes'),
('4939', 'Otros tipos of transporte terrestre of pasajeros n'),
('494', 'Transporte of mercancías por carretera y servicios of mudanza'),
('4941', 'Transporte of mercancías por carretera'),
('4942', 'Servicios of mudanzas'),
('495', 'Transporte por tubería'),
('4950', 'Transporte por tubería'),
('501', 'Transporte marítimo of pasajeros'),
('5010', 'Transporte marítimo of pasajeros'),
('502', 'Transporte marítimo of mercancías'),
('5020', 'Transporte marítimo of mercancías'),
('503', 'Transporte of pasajeros por vías navegables interiores'),
('5030', 'Transporte of pasajeros por vías navegables interiores'),
('504', 'Transporte of mercancías por vías navegables interiores'),
('5040', 'Transporte of mercancías por vías navegables interiores'),
('511', 'Transporte aéreo of pasajeros'),
('5110', 'Transporte aéreo of pasajeros'),
('512', 'Transporte aéreo of mercancías y transporte espacial'),
('5121', 'Transporte aéreo of mercancías'),
('5122', 'Transporte espacial'),
('521', 'Depósito y almacenamiento'),
('5210', 'Depósito y almacenamiento'),
('522', 'Actividades auxiliares del transporte'),
('5221', 'Actividades auxiliares del transporte terrestre'),
('5222', 'Actividades auxiliares del transporte marítimo y por vías navegables  interiores'),
('5223', 'Actividades auxiliares del transporte aéreo'),
('5224', 'Manipulación of mercancías   INE'),
('5225', 'Actividades of servicios logísticos'),
('5226', 'Otras actividades auxiliares del transporte'),
('523', 'Actividades of intermediación para el transporte'),
('5231', 'Actividades of intermediación para el transporte of mercancías'),
('5232', 'Actividades of intermediación para el transporte of pasajeros'),
('531', 'Actividades postales sometidas a la obligación del servicio universal'),
('5310', 'Actividades postales sometidas a la obligación del servicio universal'),
('532', 'Otras actividades postales y of mensajería'),
('5320', 'Otras actividades postales y of mensajería'),
('533', 'Servicios of intermediación para las actividades postales y of  mensajería'),
('5330', 'Servicios of intermediación para las actividades postales y of  mensajería   I HOSTELERÍA'),
('551', 'Hoteles y alojamientos similares'),
('5510', 'Hoteles y alojamientos similares'),
('552', 'Alojamientos turísticos y otros alojamientos of corta estancia'),
('5520', 'Alojamientos turísticos y otros alojamientos of corta estancia'),
('553', 'Campings y aparcamientos para caravanas'),
('5530', 'Campings y aparcamientos para caravanas'),
('554', 'Actividades of intermediación para los servicios of alojamiento'),
('5540', 'Actividades of intermediación para los servicios of alojamiento'),
('559', 'Otros servicios of alojamiento'),
('5590', 'Otros servicios of alojamiento'),
('561', 'Restaurantes y puestos of comidas'),
('5611', 'Restaurantes'),
('5612', 'Puestos of comidas'),
('562', 'Servicios of catering y otros servicios of comidas'),
('5621', 'Servicios ocasionales of catering'),
('5622', 'Servicios regulares of catering y otros servicios of comidas   INE'),
('563', 'Servicios of bebidas'),
('5630', 'Servicios of bebidas'),
('564', 'Actividades of intermediación para los servicios of comidas y bebidas'),
('5640', 'Actividades of intermediación para los servicios of comidas y bebidas   J ACTIVIDADES DE EDICIÓN, RADIODIFUSIÓN Y PRODUCCIÓN Y  DISTRIBUCIÓN DE CONTENIDOS'),
('581', 'Edición of libros, periódicos y otras actividades editoriales, excepto la  edición of programas informáticos'),
('5811', 'Edición of libros'),
('5812', 'Edición of periódicos'),
('5813', 'Edición of revistas'),
('5819', 'Otras actividades editoriales, excepto la edición of programas  informáticos'),
('582', 'Edición of programas informáticos'),
('5821', 'Edición of videojuegos'),
('5829', 'Edición of otros programas informáticos'),
('591', 'Actividades cinematográficas, of vídeo y of programas of televisión'),
('5912', 'Actividades of posproducción cinematográfica, of vídeo y of programas  of televisión'),
('5914', 'Actividades of exhibición cinematográfica'),
('5915', 'Actividades of producción cinematográfica y of vídeo'),
('5916', 'Actividades of producción of programas of televisión'),
('5917', 'Actividades of distribución cinematográfica y of vídeo, excepto of  programas of televisión'),
('5918', 'Actividades of distribución of programas of televisión'),
('592', 'Actividades of grabación of sonido y edición musical'),
('5920', 'Actividades of grabación of sonido y edición musical'),
('601', 'Actividades of radiodifusión y distribución of audio'),
('6010', 'Actividades of radiodifusión y distribución of audio   INE'),
('602', 'Actividades of programación of televisión, emisión y distribución of  vídeos'),
('6020', 'Actividades of programación of televisión, emisión y distribución of  vídeos'),
('603', 'Actividades of las agencias of noticias y otras actividades of  distribución of contenidos'),
('6031', 'Actividades of las agencias of noticias'),
('6039', 'Otras actividades of distribución of contenidos   K TELECOMUNICACIONES, PROGRAMACIÓN INFORMÁTICA,  CONSULTORÍA, INFRAESTRUCTURA INFORMÁTICA Y OTROS  SERVICIOS DE INFORMACIÓN'),
('611', 'Actividades of telecomunicaciones por cable, inalámbricas y por satélite'),
('6110', 'Actividades of telecomunicaciones por cable, inalámbricas y por satélite'),
('612', 'Actividades of reventa of telecomunicaciones y servicios of  intermediación para telecomunicaciones'),
('6120', 'Actividades of reventa of telecomunicaciones y servicios of  intermediación para telecomunicaciones'),
('619', 'Otras actividades of telecomunicaciones'),
('6190', 'Otras actividades of telecomunicaciones'),
('621', 'Actividades of programación informática'),
('6210', 'Actividades of programación informática'),
('622', 'Actividades of consultoría informática y gestión of instalaciones  informáticas'),
('6220', 'Actividades of consultoría informática y gestión of instalaciones  informáticas'),
('629', 'Otros servicios relacionados con las tecnologías of la información y la  informática'),
('6290', 'Otros servicios relacionados con las tecnologías of la información y la  informática'),
('631', 'Infraestructura informática, procesamiento of datos, hosting y  actividades relacionadas'),
('6310', 'Infraestructura informática, procesamiento of datos, hosting y  actividades relacionadas   INE'),
('639', 'Actividades of portales of búsqueda in la web y otras actividades of  servicios of información'),
('6391', 'Actividades of portales of búsqueda in la web'),
('6392', 'Otros servicios of información   L ACTIVIDADES FINANCIERAS Y DE SEGUROS'),
('641', 'Intermediación monetaria'),
('6411', 'Banca central'),
('6419', 'Otra intermediación monetaria'),
('642', 'Actividades of sociedades holding y of sociedades instrumentales of  financiación'),
('6421', 'Actividades of sociedades holding'),
('6422', 'Actividades of sociedades instrumentales of financiación'),
('643', 'Actividades of inversión colectiva, of fondos y of entidades financieras  similares'),
('6431', 'Actividades of fondos of inversión monetarios y no monetarios'),
('6432', 'Actividades of cuentas fiduciarias, patrimoniales y of agencia'),
('649', 'Otros servicios financieros, excepto seguros y fondos of pensiones'),
('6491', 'Arrendamiento financiero'),
('6492', 'Otras actividades crediticias'),
('6499', 'Otros servicios financieros, excepto seguros y fondos of pensiones  n'),
('651', 'Seguros'),
('6511', 'Seguros of vida'),
('6512', 'Seguros distintos of los seguros of vida'),
('652', 'Reaseguros'),
('6520', 'Reaseguros'),
('653', 'Fondos of pensiones'),
('6530', 'Fondos of pensiones'),
('661', 'Actividades auxiliares a los servicios financieros, excepto seguros y  fondos of pensiones   INE'),
('6611', 'Administración of mercados financieros'),
('6613', 'Actividades of financiación participativa'),
('6614', 'Otras actividades of intermediación in operaciones con valores y otros  activos'),
('6619', 'Otras actividades auxiliares a los servicios financieros, excepto seguros y  fondos of pensiones'),
('662', 'Actividades auxiliares a seguros y fondos of pensiones'),
('6621', 'Evaluación of riesgos y daños'),
('6622', 'Actividades of agentes y corredores of seguros'),
('6629', 'Actividades auxiliares a seguros y fondos of pensiones n'),
('663', 'Actividades of gestión of fondos'),
('6630', 'Actividades of gestión of fondos   M ACTIVIDADES INMOBILIARIAS'),
('681', 'Actividades inmobiliarias por cuenta propia y promoción inmobiliaria'),
('6811', 'Compraventa of bienes inmobiliarios por cuenta propia'),
('6812', 'Promoción inmobiliaria'),
('682', 'Alquiler of bienes inmobiliarios por cuenta propia'),
('6820', 'Alquiler of bienes inmobiliarios por cuenta propia'),
('683', 'Actividades inmobiliarias por cuenta of terceros'),
('6831', 'Servicios of intermediación para actividades inmobiliarias'),
('6832', 'Otras actividades inmobiliarias por cuenta of terceros   N ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS'),
('691', 'Actividades jurídicas'),
('6910', 'Actividades jurídicas'),
('692', 'Actividades of contabilidad, teneduría of libros, auditoría y asesoría  fiscal'),
('6920', 'Actividades of contabilidad, teneduría of libros, auditoría y asesoría  fiscal'),
('701', 'Actividades of las sedes centrales'),
('7010', 'Actividades of las sedes centrales   INE'),
('702', 'Otras actividades of consultoría of gestión empresarial'),
('7020', 'Otras actividades of consultoría of gestión empresarial'),
('711', 'Servicios técnicos of arquitectura e ingeniería y otras actividades  relacionadas con el asesoramiento técnico'),
('7111', 'Servicios técnicos of arquitectura'),
('7112', 'Servicios técnicos of ingeniería y otras actividades relacionadas con el  asesoramiento técnico'),
('712', 'Ensayos y análisis técnicos'),
('7120', 'Ensayos y análisis técnicos'),
('721', 'Investigación y desarrollo experimental in ciencias naturales y técnicas'),
('7210', 'Investigación y desarrollo experimental in ciencias naturales y técnicas'),
('722', 'Investigación y desarrollo experimental in ciencias sociales y  humanidades'),
('7220', 'Investigación y desarrollo experimental in ciencias sociales y  humanidades'),
('731', 'Publicidad'),
('7311', 'Actividades of las agencias of publicidad'),
('7312', 'Servicios of representación of medios of comunicación'),
('732', 'Estudios of mercado y realización of encuestas of opinión pública'),
('7320', 'Estudios of mercado y realización of encuestas of opinión pública'),
('733', 'Relaciones públicas y comunicación'),
('7330', 'Relaciones públicas y comunicación'),
('741', 'Actividades of diseño especializado'),
('7411', 'Actividades of diseño of productos industriales y moda'),
('7412', 'Actividades of diseño gráfico y of comunicación visual'),
('7413', 'Actividades of diseño of interiores'),
('7414', 'Otras actividades of diseño especializado'),
('742', 'Actividades of fotografía   INE'),
('7420', 'Actividades of fotografía'),
('743', 'Actividades of traducción e interpretación'),
('7430', 'Actividades of traducción e interpretación'),
('749', 'Otras actividades profesionales, científicas y técnicas n'),
('7491', 'Actividades of los agentes of patentes y of los servicios of marketing'),
('7499', 'Todas las demás actividades profesionales, científicas y técnicas n'),
('750', 'Actividades veterinarias'),
('7500', 'Actividades veterinarias   O ACTIVIDADES ADMINISTRATIVAS Y SERVICIOS AUXILIARES'),
('771', 'Alquiler of vehículos of motor'),
('7711', 'Alquiler of automóviles y vehículos of motor ligeros'),
('7712', 'Alquiler of camiones'),
('772', 'Alquiler of efectos personales y artículos of uso doméstico'),
('7721', 'Alquiler of artículos of ocio y deportivos'),
('7722', 'Alquiler of efectos personales y artículos of uso doméstico'),
('773', 'Alquiler of otra maquinaria, equipos y bienes tangibles'),
('7731', 'Alquiler of maquinaria y equipo of uso agrícola'),
('7732', 'Alquiler of maquinaria y equipo para la construcción e ingeniería civil'),
('7733', 'Alquiler of maquinaria y equipo of oficina y ordenadores'),
('7734', 'Alquiler of medios of navegación'),
('7735', 'Alquiler of medios of transporte aéreo'),
('7739', 'Alquiler of otra maquinaria, equipos y bienes tangibles n'),
('774', 'Arrendamiento of la propiedad intelectual y productos similares, excepto  obras protegidas por derechos of autor'),
('7740', 'Arrendamiento of la propiedad intelectual y productos similares, excepto  obras protegidas por derechos of autor'),
('775', 'Servicios of intermediación para el alquiler of bienes tangibles y of  activos intangibles no financieros'),
('7751', 'Servicios of intermediación para el alquiler of automóviles,  autocaravanas y remolques'),
('7752', 'Servicios of intermediación para el alquiler of otros bienes tangibles y  of activos intangibles no financieros   INE'),
('781', 'Actividades of las agencias of colocación'),
('7810', 'Actividades of las agencias of colocación'),
('782', 'Actividades of las empresas of trabajo temporal y otra provisión of  recursos humanos'),
('7820', 'Actividades of las empresas of trabajo temporal y otra provisión of  recursos humanos'),
('791', 'Actividades of agencias of viajes y operadores turísticos'),
('7911', 'Actividades of las agencias of viajes'),
('7912', 'Actividades of los operadores turísticos'),
('799', 'Otros servicios of reservas y actividades relacionadas con los mismos'),
('7990', 'Otros servicios of reservas y actividades relacionadas con los mismos'),
('800', 'Servicios of investigación y seguridad'),
('8001', 'Servicios of investigación y seguridad privados'),
('8009', 'Servicios of seguridad n'),
('811', 'Servicios integrales a edificios e instalaciones'),
('8110', 'Servicios integrales a edificios e instalaciones'),
('812', 'Actividades of limpieza'),
('8121', 'Limpieza general of edificios'),
('8122', 'Otras actividades of limpieza industrial y of edificios'),
('8123', 'Otras actividades of limpieza'),
('813', 'Actividades of jardinería'),
('8130', 'Actividades of jardinería'),
('821', 'Actividades administrativas y auxiliares of oficina'),
('8210', 'Actividades administrativas y auxiliares of oficina'),
('822', 'Actividades of los centros of llamadas'),
('8220', 'Actividades of los centros of llamadas   INE'),
('823', 'Organización of convenciones y ferias of muestras'),
('8230', 'Organización of convenciones y ferias of muestras'),
('824', 'Actividades of intermediación para servicios of apoyo a las empresas  n'),
('8240', 'Actividades of intermediación para servicios of apoyo a las empresas  n'),
('829', 'Otras actividades of apoyo a las empresas n'),
('8291', 'Actividades of las agencias of cobros y of las oficinas of crédito'),
('8292', 'Actividades of envasado y empaquetado'),
('8299', 'Otras actividades of apoyo a las empresas n'),
('841', 'Administración pública y of la política económica, social y  medioambiental'),
('8411', 'Actividades generales of la administración pública'),
('8412', 'Regulación of los servicios sanitarios, educativos y culturales y otros  servicios sociales'),
('8413', 'Regulación of la actividad económica y contribución a su mayor  eficiencia'),
('842', 'Prestación of servicios a la comunidad in general'),
('8421', 'Asuntos exteriores'),
('8422', 'Defensa'),
('8423', 'Justicia'),
('8424', 'Orden público y seguridad'),
('8425', 'Servicios of extinción of incendios'),
('843', 'Seguridad social obligatoria'),
('8430', 'Seguridad social obligatoria   Q EDUCACIÓN'),
('851', 'Educación preprimaria'),
('8510', 'Educación preprimaria'),
('852', 'Educación primaria'),
('8520', 'Educación primaria   INE'),
('853', 'Educación secundaria y educación postsecundaria no terciaria'),
('8531', 'Educación secundaria general'),
('8532', 'Educación secundaria profesional'),
('8533', 'Educación postsecundaria no terciaria'),
('854', 'Educación terciaria'),
('8541', 'Educación universitaria'),
('8542', 'Educación terciaria no universitaria'),
('855', 'Otra educación'),
('8551', 'Educación deportiva y recreativa'),
('8552', 'Educación cultural'),
('8553', 'Actividades of las escuelas of conducción y pilotaje'),
('8559', 'Otra educación n'),
('856', 'Actividades auxiliares a la educación'),
('8561', 'Actividades of servicios of intermediación para cursos y tutores'),
('8569', 'Actividades auxiliares a la educación n'),
('861', 'Actividades hospitalarias'),
('8610', 'Actividades hospitalarias'),
('862', 'Actividades médicas y odontológicas'),
('8621', 'Actividades of medicina general y of medicina familiar y comunitaria'),
('8622', 'Actividades of otras especialidades médicas'),
('8623', 'Actividades odontológicas'),
('869', 'Otras actividades sanitarias'),
('8691', 'Servicios of diagnóstico por la imagen y actividades of laboratorio  médico'),
('8692', 'Transporte of pacientes in ambulancia'),
('8693', 'Actividades of psicólogos y psicoterapeutas, excepto médicos'),
('8694', 'Actividades of enfermería y enfermería obstétrica'),
('8695', 'Actividades of fisioterapia'),
('8696', 'Actividades of medicina tradicional, complementaria y alternativa'),
('8697', 'Actividades of intermediación para servicios médicos, odontológicos y  otros servicios sanitarios   INE'),
('8699', 'Otras actividades sanitarias n'),
('871', 'Asistencia in establecimientos residenciales con cuidados sanitarios'),
('8710', 'Asistencia in establecimientos residenciales con cuidados sanitarios'),
('872', 'Asistencia in establecimientos residenciales para personas que padecen  una enfermedad mental o una drogodependencia o que han recibido un  diagnóstico al respecto'),
('8720', 'Asistencia in establecimientos residenciales para personas que padecen  una enfermedad mental o una drogodependencia o que han recibido un  diagnóstico al respecto'),
('873', 'Asistencia in establecimientos residenciales para personas mayores o  con discapacidad física'),
('8731', 'Asistencia in establecimientos residenciales para personas mayores'),
('8732', 'Asistencia in establecimientos residenciales para personas con  discapacidad física'),
('879', 'Otras actividades of asistencia in establecimientos residenciales'),
('8791', 'Servicios of intermediación para actividades of asistencia in  establecimientos residenciales'),
('8799', 'Otro tipo of asistencia in establecimientos residenciales n'),
('881', 'Actividades of servicios sociales sin alojamiento para personas mayores  o con discapacidad'),
('8811', 'Actividades of servicios sociales sin alojamiento para personas mayores'),
('8812', 'Actividades of servicios sociales sin alojamiento para personas con  discapacidad'),
('889', 'Otras actividades of servicios sociales sin alojamiento'),
('8891', 'Actividades of cuidado diurno of niños'),
('8899', 'Otras actividades of servicios sociales sin alojamiento n'),
('901', 'Actividades of creación artística'),
('9011', 'Actividades of creación literaria y composición musical'),
('9012', 'Actividades of creación of artes visuales'),
('9013', 'Otras actividades of creación artística'),
('902', 'Actividades of artes escénicas'),
('9020', 'Actividades of artes escénicas   INE'),
('903', 'Actividades of apoyo a la creación artística y a las artes escénicas'),
('9031', 'Gestión of instalaciones para actividades artísticas y artes escénicas'),
('9039', 'Otras actividades of apoyo a la creación artística y a las artes escénicas'),
('911', 'Actividades of bibliotecas y archivos'),
('9111', 'Actividades of bibliotecas'),
('9112', 'Actividades of archivos'),
('912', 'Actividades of museos, colecciones of arte, sitios históricos y  monumentos'),
('9121', 'Actividades of museos y of colecciones'),
('9122', 'Actividades of sitios históricos y monumentos'),
('913', 'Conservación, restauración y otras actividades of apoyo al patrimonio  cultural'),
('9130', 'Conservación, restauración y otras actividades of apoyo al patrimonio  cultural'),
('914', 'Actividades of los jardines botánicos, parques zoológicos y reservas  naturales'),
('9141', 'Actividades of los jardines botánicos y los parques zoológicos'),
('9142', 'Actividades of las reservas naturales'),
('920', 'Actividades of juegos of azar y apuestas'),
('9200', 'Actividades of juegos of azar y apuestas'),
('931', 'Actividades deportivas'),
('9311', 'Gestión of instalaciones deportivas'),
('9312', 'Actividades of los clubes deportivos'),
('9313', 'Actividades of los centros deportivos'),
('9319', 'Actividades deportivas n'),
('932', 'Otras actividades recreativas y of entretenimiento'),
('9321', 'Actividades of los parques of atracciones y los parques temáticos'),
('9329', 'Actividades recreativas y of entretenimiento n'),
('941', 'Actividades of organizaciones empresariales, profesionales y patronales'),
('9411', 'Actividades of organizaciones empresariales y patronales'),
('9412', 'Actividades of organizaciones profesionales'),
('942', 'Actividades sindicales'),
('9420', 'Actividades sindicales'),
('949', 'Otras actividades asociativas'),
('9491', 'Actividades of organizaciones religiosas'),
('9492', 'Actividades of organizaciones políticas'),
('9499', 'Otras actividades asociativas n'),
('951', 'Reparación y mantenimiento of ordenadores y equipos of comunicación'),
('9510', 'Reparación y mantenimiento of ordenadores y equipos of comunicación'),
('952', 'Reparación y mantenimiento of efectos personales y artículos of uso  doméstico'),
('9521', 'Reparación y mantenimiento of aparatos electrónicos of uso doméstico'),
('9522', 'Reparación y mantenimiento of electrodomésticos y of equipos para el  hogar y el jardín'),
('9523', 'Reparación y mantenimiento of calzado y artículos of cuero'),
('9524', 'Reparación y mantenimiento of muebles y artículos of menaje'),
('9525', 'Reparación y mantenimiento of relojes y joyería'),
('9529', 'Reparación y mantenimiento of efectos personales y artículos of uso  doméstico n'),
('953', 'Reparación y mantenimiento of vehículos of motor y motocicletas'),
('9531', 'Reparación y mantenimiento of vehículos of motor'),
('9532', 'Reparación y mantenimiento of motocicletas'),
('954', 'Actividades of intermediación para reparación y mantenimiento of  ordenadores, artículos personales y enseres domésticos y vehículos of  motor y motocicletas'),
('9540', 'Actividades of intermediación para reparación y mantenimiento of  ordenadores, articles personales y enseres domésticos y vehículos of  motor y motocicletas'),
('961', 'Lavado y limpieza of prendas of tela y of piel'),
('9610', 'Lavado y limpieza of prendas of tela y of piel   INE'),
('962', 'Peluquería, tratamientos of belleza, spas y actividades similares'),
('9621', 'Peluquerías y barberías'),
('9622', 'Actividades of cuidados of belleza y otras actividades of tratamiento of  belleza'),
('9623', 'Actividades of spas, saunas y baños turcos'),
('963', 'Pompas fúnebres y actividades relacionadas'),
('9630', 'Pompas fúnebres y actividades relacionadas'),
('964', 'Actividades of intermediación para servicios personales'),
('9640', 'Actividades of intermediación para servicios personales'),
('969', 'Otros servicios personales'),
('9691', 'Prestación of servicios personales domésticos'),
('9699', 'Otros servicios personales n'),
('970', 'Actividades of los hogares como empleadores of personal doméstico'),
('9700', 'Actividades of los hogares como empleadores of personal doméstico'),
('981', 'Actividades of los hogares como productores of bienes para uso propio'),
('9810', 'Actividades of los hogares como productores of bienes para uso propio'),
('982', 'Actividades of los hogares como productores of servicios para uso  propio'),
('9820', 'Actividades of los hogares como productores of servicios para uso  propio   V ORGANISMOS EXTRATERRITORIALES'),
('990', 'Actividades of organizaciones y organismos extraterritoriales'),
('9900', 'Actividades of organizaciones y organismos extraterritoriales   INE');

-- 1. TABLA: usuarios (No tiene dependencias, se crea primero)
CREATE TABLE IF NOT EXISTS usuarios (
    id UUID PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    nif_cif VARCHAR(20) UNIQUE NOT NULL,
    domicilio_fiscal TEXT NOT NULL,
    poblacion VARCHAR(100),
    provincia VARCHAR(100),
    codigo_postal VARCHAR(20),
    email VARCHAR(150) UNIQUE NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    cnae VARCHAR(10),
    iae VARCHAR(20),
    iban VARCHAR(50),
    profile_picture VARCHAR(255),
    gmail_token VARCHAR(255),
    irpf_rate FLOAT DEFAULT 0.20,
    tarifa_hora FLOAT DEFAULT 0.00,
    precio_servicio FLOAT DEFAULT 0.00,
    desc_servicio VARCHAR(100) DEFAULT 'Servicio Base',
    precio_producto FLOAT DEFAULT 0.00,
    desc_producto VARCHAR(100) DEFAULT 'Producto',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. TABLA: calendario_eventos (Depende de usuarios)
CREATE TABLE IF NOT EXISTS calendario_eventos (
    id UUID PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT,
    tipo VARCHAR(20) DEFAULT 'personal',
    color VARCHAR(10) DEFAULT '#4a90e2',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABLA: clientes (Depende de usuarios)
CREATE TABLE IF NOT EXISTS clientes (
    id UUID PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre_empresa VARCHAR(150) NOT NULL,
    nif_cif VARCHAR(20) NOT NULL,
    telefono VARCHAR(20),
    email VARCHAR(150),
    direccion_fiscal TEXT NOT NULL,
    poblacion VARCHAR(100),
    provincia VARCHAR(100),
    codigo_postal VARCHAR(20),
    direccion_comercial TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. TABLA: productos (Depende de usuarios)
CREATE TABLE IF NOT EXISTS productos (
    id UUID PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    precio_unitario FLOAT NOT NULL DEFAULT 0.0,
    tipo VARCHAR(50) NOT NULL DEFAULT 'Servicio',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. TABLA: gastos (Depende de usuarios)
CREATE TABLE IF NOT EXISTS gastos (
    id UUID PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    proveedor VARCHAR(255),
    concepto TEXT,
    importe_total FLOAT NOT NULL DEFAULT 0.0,
    url_ticket VARCHAR(500),
    status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
    clarification_reason TEXT,
    is_deducible BOOLEAN DEFAULT TRUE,
    porcentaje_iva INTEGER DEFAULT 100,
    porcentaje_irpf INTEGER DEFAULT 100,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. TABLA: facturas (Depende de usuarios y clientes)
CREATE TABLE IF NOT EXISTS facturas (
    id UUID PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    cliente_id UUID NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    numero_factura_secuencial INTEGER NOT NULL,
    codigo_factura VARCHAR(50) NOT NULL,
    fecha_expedicion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_vencimiento TIMESTAMP WITH TIME ZONE,
    total_base FLOAT NOT NULL,
    total_impuestos FLOAT NOT NULL,
    importe_total FLOAT NOT NULL,
    json_lineas JSONB NOT NULL,
    url_pdf VARCHAR(500),
    hash_registro VARCHAR(64) NOT NULL,
    hash_anterior VARCHAR(64),
    estado_verifactu VARCHAR(20) DEFAULT 'Pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT _usuario_num_factura_uc UNIQUE (usuario_id, numero_factura_secuencial)
);

-- 7. TABLA: presupuestos (Depende de usuarios y clientes)
CREATE TABLE IF NOT EXISTS presupuestos (
    id UUID PRIMARY KEY,
    usuario_id UUID NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    cliente_id UUID NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
    numero_presupuesto_secuencial INTEGER NOT NULL,
    codigo_presupuesto VARCHAR(50) NOT NULL,
    fecha_expedicion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_validez TIMESTAMP WITH TIME ZONE,
    total_base FLOAT NOT NULL,
    total_impuestos FLOAT NOT NULL,
    importe_total FLOAT NOT NULL,
    json_lineas JSONB NOT NULL,
    url_pdf VARCHAR(500),
    estado VARCHAR(20) DEFAULT 'Pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT _usuario_num_presupuesto_uc UNIQUE (usuario_id, numero_presupuesto_secuencial)
);

-- 8. TABLA: subvenciones (Para RAG y búsquedas semánticas)
CREATE TABLE IF NOT EXISTS subvenciones (
    id UUID PRIMARY KEY,
    id_bdns VARCHAR(100) UNIQUE NOT NULL,
    titulo TEXT NOT NULL,
    cnae_target VARCHAR(50),
    apto_autonomos BOOLEAN,
    fecha_publicacion TIMESTAMP WITH TIME ZONE,
    fecha_cierre TIMESTAMP WITH TIME ZONE,
    texto_completo TEXT NOT NULL,
    embedding vector(768)
);

-- 9. TABLA: reglas_deduccion (Para RAG de IAE y gastos)
CREATE TABLE IF NOT EXISTS reglas_deduccion (
    id UUID PRIMARY KEY,
    contenido TEXT NOT NULL,
    fuente VARCHAR(255) NOT NULL,
    iae_contexto VARCHAR(50),
    embedding vector(768)
);

-- FUNCIÓN: Sincronizar desc_producto con CNAE
CREATE OR REPLACE FUNCTION update_user_desc_producto()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.cnae IS NOT NULL THEN
        SELECT descripcion INTO NEW.desc_producto
        FROM cnae_mappings
        WHERE codigo = NEW.cnae;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- TRIGGER: Actualizar antes de insertar o modificar un usuario
DROP TRIGGER IF EXISTS trg_update_user_desc_producto ON usuarios;
CREATE TRIGGER trg_update_user_desc_producto
BEFORE INSERT OR UPDATE OF cnae ON usuarios
FOR EACH ROW
EXECUTE FUNCTION update_user_desc_producto();